=== OPTIMALSYSTEMS/yuuvis-form-modelling-draft/src/assets/schema.json
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "$ref": "#/definitions/Model",
  "definitions": {
    "Model": {
      "type": "object",
      "properties": {
        "name": {
          "type": "string"
        },
        "label": {
          "type": "string"
        },
        "script": {
          "type": "string"
        },
        "description": {
          "type": "string"
        },
        "situation": {
          "type": "string",
          "enum": [
            "EDIT",
            "SEARCH",
            "CREATE"
          ]
        },
        "elements": {
          "type": "array",
          "minItems": 2,
          "items": [
            {
              "$ref": "#/definitions/CoreSection"
            },
            {
              "$ref": "#/definitions/DataSection"
            }
          ],
          "maxItems": 2
        }
      },
      "required": [
        "name",
        "situation",
        "elements"
      ],
      "additionalProperties": false
    },
    "CoreSection": {
      "type": "object",
      "properties": {
        "name": {
          "type": "string",
          "const": "core"
        },
        "label": {
          "type": "string"
        },
        "type": {
          "type": "string",
          "const": "o2mGroup"
        },
        "elements": {
          "type": "array",
          "items": {
            "anyOf": [
              {
                "$ref": "#/definitions/Group"
              },
              {
                "$ref": "#/definitions/Stack"
              },
              {
                "$ref": "#/definitions/FormElementBoolean"
              },
              {
                "$ref": "#/definitions/FormElementDatetime"
              },
              {
                "$ref": "#/definitions/FormElementDecimal"
              },
              {
                "$ref": "#/definitions/FormElementInteger"
              },
              {
                "$ref": "#/definitions/FormElementString"
              },
              {
                "$ref": "#/definitions/FormElementTable"
              }
            ]
          }
        },
        "layout": {
          "type": "object",
          "properties": {
            "align": {
              "type": "string",
              "enum": [
                "row",
                "column"
              ]
            }
          },
          "additionalProperties": false
        }
      },
      "required": [
        "elements",
        "name",
        "type"
      ],
      "additionalProperties": false
    },
    "Group": {
      "type": "object",
      "properties": {
        "name": {
          "type": "string"
        },
        "label": {
          "type": "string"
        },
        "type": {
          "type": "string",
          "const": "o2mGroup"
        },
        "elements": {
          "type": "array",
          "items": {
            "anyOf": [
              {
                "$ref": "#/definitions/Group"
              },
              {
                "$ref": "#/definitions/Stack"
              },
              {
                "$ref": "#/definitions/FormElementBoolean"
              },
              {
                "$ref": "#/definitions/FormElementDatetime"
              },
              {
                "$ref": "#/definitions/FormElementDecimal"
              },
              {
                "$ref": "#/definitions/FormElementInteger"
              },
              {
                "$ref": "#/definitions/FormElementString"
              },
              {
                "$ref": "#/definitions/FormElementTable"
              }
            ]
          }
        },
        "layout": {
          "type": "object",
          "properties": {
            "align": {
              "type": "string",
              "enum": [
                "row",
                "column"
              ]
            }
          },
          "additionalProperties": false
        }
      },
      "required": [
        "type",
        "elements"
      ],
      "additionalProperties": false
    },
    "Stack": {
      "type": "object",
      "properties": {
        "name": {
          "type": "string"
        },
        "type": {
          "type": "string",
          "const": "o2mGroupStack"
        },
        "elements": {
          "type": "array",
          "items": {
            "$ref": "#/definitions/Group"
          }
        }
      },
      "required": [
        "name",
        "type",
        "elements"
      ],
      "additionalProperties": false
    },
    "FormElementBoolean": {
      "type": "object",
      "properties": {
        "name": {
          "type": "string"
        },
        "label": {
          "type": "string"
        },
        "description": {
          "type": "string"
        },
        "type": {
          "type": "string",
          "const": "boolean"
        },
        "cardinality": {
          "type": "string",
          "enum": [
            "single",
            "multi"
          ]
        },
        "classifications": {
          "type": "array",
          "items": {
            "type": "string"
          }
        },
        "required": {
          "type": "boolean"
        },
        "readonly": {
          "type": "boolean"
        },
        "defaultvalue": {
          "type": "boolean"
        },
        "tristate": {
          "type": "boolean"
        }
      },
      "required": [
        "cardinality",
        "name",
        "type"
      ],
      "additionalProperties": false
    },
    "FormElementDatetime": {
      "type": "object",
      "properties": {
        "name": {
          "type": "string"
        },
        "label": {
          "type": "string"
        },
        "description": {
          "type": "string"
        },
        "type": {
          "type": "string",
          "const": "datetime"
        },
        "cardinality": {
          "type": "string",
          "enum": [
            "single",
            "multi"
          ]
        },
        "classifications": {
          "type": "array",
          "items": {
            "type": "string"
          }
        },
        "required": {
          "type": "boolean"
        },
        "readonly": {
          "type": "boolean"
        },
        "defaultvalue": {
          "anyOf": [
            {
              "type": "array",
              "items": {
                "type": "string"
              }
            },
            {
              "type": "string"
            }
          ]
        },
        "resolution": {
          "type": "string",
          "const": "date"
        }
      },
      "required": [
        "cardinality",
        "name",
        "type"
      ],
      "additionalProperties": false
    },
    "FormElementDecimal": {
      "type": "object",
      "properties": {
        "name": {
          "type": "string"
        },
        "label": {
          "type": "string"
        },
        "description": {
          "type": "string"
        },
        "type": {
          "type": "string",
          "const": "decimal"
        },
        "cardinality": {
          "type": "string",
          "enum": [
            "single",
            "multi"
          ]
        },
        "classifications": {
          "type": "array",
          "items": {
            "type": "string"
          }
        },
        "required": {
          "type": "boolean"
        },
        "readonly": {
          "type": "boolean"
        },
        "defaultvalue": {
          "anyOf": [
            {
              "type": "array",
              "items": {
                "type": "number"
              }
            },
            {
              "type": "number"
            }
          ]
        },
        "maxValue": {
          "type": "number"
        },
        "minValue": {
          "type": "number"
        },
        "precision": {
          "type": "number"
        },
        "scale": {
          "type": "number"
        },
        "grouping": {
          "type": "boolean"
        },
        "pattern": {
          "type": "string"
        }
      },
      "required": [
        "cardinality",
        "name",
        "type"
      ],
      "additionalProperties": false
    },
    "FormElementInteger": {
      "type": "object",
      "properties": {
        "name": {
          "type": "string"
        },
        "label": {
          "type": "string"
        },
        "description": {
          "type": "string"
        },
        "type": {
          "type": "string",
          "const": "integer"
        },
        "cardinality": {
          "type": "string",
          "enum": [
            "single",
            "multi"
          ]
        },
        "classifications": {
          "type": "array",
          "items": {
            "type": "string"
          }
        },
        "required": {
          "type": "boolean"
        },
        "readonly": {
          "type": "boolean"
        },
        "defaultvalue": {
          "anyOf": [
            {
              "type": "array",
              "items": {
                "type": "number"
              }
            },
            {
              "type": "number"
            }
          ]
        },
        "maxValue": {
          "type": "number"
        },
        "minValue": {
          "type": "number"
        },
        "precision": {
          "type": "number"
        },
        "grouping": {
          "type": "boolean"
        },
        "pattern": {
          "type": "string"
        }
      },
      "required": [
        "cardinality",
        "name",
        "type"
      ],
      "additionalProperties": false
    },
    "FormElementString": {
      "type": "object",
      "properties": {
        "name": {
          "type": "string"
        },
        "label": {
          "type": "string"
        },
        "description": {
          "type": "string"
        },
        "type": {
          "type": "string",
          "const": "string"
        },
        "cardinality": {
          "type": "string",
          "enum": [
            "single",
            "multi"
          ]
        },
        "classifications": {
          "type": "array",
          "items": {
            "type": "string"
          }
        },
        "required": {
          "type": "boolean"
        },
        "readonly": {
          "type": "boolean"
        },
        "defaultvalue": {
          "anyOf": [
            {
              "type": "array",
              "items": {
                "type": "string"
              }
            },
            {
              "type": "string"
            }
          ]
        },
        "maxLength": {
          "type": "number"
        },
        "minLength": {
          "type": "number"
        },
        "rows": {
          "type": "number"
        },
        "options": {
          "anyOf": [
            {
              "type": "array",
              "items": {
                "type": "string"
              }
            },
            {
              "type": "string"
            }
          ]
        },
        "regex": {
          "type": "string"
        }
      },
      "required": [
        "cardinality",
        "name",
        "type"
      ],
      "additionalProperties": false
    },
    "FormElementTable": {
      "type": "object",
      "properties": {
        "name": {
          "type": "string"
        },
        "label": {
          "type": "string"
        },
        "description": {
          "type": "string"
        },
        "type": {
          "type": "string",
          "const": "table"
        },
        "cardinality": {
          "type": "string",
          "enum": [
            "single",
            "multi"
          ]
        },
        "classifications": {
          "type": "array",
          "items": {
            "type": "string"
          }
        },
        "required": {
          "type": "boolean"
        },
        "readonly": {
          "type": "boolean"
        }
      },
      "required": [
        "cardinality",
        "name",
        "type"
      ],
      "additionalProperties": false
    },
    "DataSection": {
      "type": "object",
      "properties": {
        "name": {
          "type": "string",
          "const": "data"
        },
        "type": {
          "type": "string",
          "const": "o2mGroupStack"
        },
        "elements": {
          "type": "array",
          "items": {
            "$ref": "#/definitions/Group"
          }
        }
      },
      "required": [
        "elements",
        "name",
        "type"
      ],
      "additionalProperties": false
    }
  }
}

=== OPTIMALSYSTEMS/yuuvis-form-modelling-draft/src/assets/test-model.json
{
    "name": "tenKolibri:qadocallsinglefields",
    "situation": "EDIT",
    "elements": [
        {
            "name": "core",
            "type": "o2mGroup",
            "elements": [
                {
                    "type": "o2mGroup",
                    "elements": [
                        {
                            "name": "appClient:clienttitle",
                            "type": "string",
                            "maxLength": 200,
                            "required": false,
                            "cardinality": "single",
                            "rows": 1,
                            "readonly": false,
                            "label": "Name",
                            "description": "07 Invoice Management"
                        },
                        {
                            "name": "appClient:clientdescription",
                            "type": "string",
                            "maxLength": 200,
                            "required": false,
                            "cardinality": "single",
                            "rows": 1,
                            "readonly": false,
                            "label": "Description"
                        }
                    ],
                    "layout": {
                        "align": "column"
                    }
                }
            ],
            "layout": {
                "align": "row"
            }
        },
        {
            "name": "data",
            "type": "o2mGroupStack",
            "elements": [
                {
                    "name": "tenKolibri:required",
                    "type": "o2mGroup",
                    "elements": [
                        {
                            "name": "tenKolibri:decsinglemin1111max9999required",
                            "type": "decimal",
                            "defaultvalue": 12.34,
                            "maxValue": 99.99,
                            "minValue": 11.11,
                            "required": true,
                            "cardinality": "single",
                            "readonly": false,
                            "label": "Decimal",
                            "description": "min 11.11 - max 99.99 - mandatory"
                        },
                        {
                            "name": "tenKolibri:strsinglemin5max10required",
                            "type": "string",
                            "maxLength": 11,
                            "minLength": 5,
                            "required": true,
                            "cardinality": "single",
                            "rows": 1,
                            "readonly": false,
                            "label": "String",
                            "description": "min 5 - max 10 - mandatory"
                        },
                        {
                            "name": "tenKolibri:intsinglemin11max99required",
                            "type": "integer",
                            "defaultvalue": 20,
                            "maxValue": 99,
                            "minValue": 11,
                            "required": true,
                            "cardinality": "single",
                            "readonly": false,
                            "label": "Integer",
                            "description": "min 11 - max 999 - mandatory"
                        },
                        {
                            "name": "tenKolibri:datesinglerequired",
                            "type": "datetime",
                            "required": true,
                            "cardinality": "single",
                            "resolution": "date",
                            "readonly": false,
                            "label": "Date1",
                            "description": "mandatory"
                        },
                        {
                            "name": "tenKolibri:datetimesinglerequired",
                            "type": "datetime",
                            "defaultvalue": "2019-04-17T14:59:00.000Z",
                            "required": true,
                            "cardinality": "single",
                            "readonly": false,
                            "label": "Date & time",
                            "description": "mandatory"
                        },
                        {
                            "name": "tenKolibri:booleanrequiredtrue",
                            "type": "boolean",
                            "defaultvalue": false,
                            "required": true,
                            "cardinality": "single",
                            "readonly": false,
                            "label": "Boolean",
                            "description": "mandatory"
                        }
                    ],
                    "layout": {
                        "align": "column"
                    },
                    "label": "Mandatory fields"
                },
                {
                    "name": "tenKolibri:notrequired",
                    "type": "o2mGroup",
                    "elements": [
                        {
                            "name": "tenKolibri:strsingle",
                            "type": "string",
                            "required": false,
                            "cardinality": "single",
                            "classifications": [
                                "appClient:summary:hidden"
                            ],
                            "rows": 1,
                            "readonly": false,
                            "label": "String",
                            "description": "unlimited: lorum ipsum lorum ipsum lorum ipsum lorum ipsum lorum ipsum lorum ipsum lorum ipsum lorum ipsum lorum ipsum  lorum ipsum"
                        },
                        {
                            "name": "tenKolibri:strregextime",
                            "type": "string",
                            "required": false,
                            "cardinality": "single",
                            "rows": 1,
                            "readonly": false,
                            "label": "Time",
                            "description": "Time format is 24 hours with hh:mm"
                        },
                        {
                            "name": "tenKolibri:decsingle",
                            "type": "decimal",
                            "defaultvalue": 0.0,
                            "required": false,
                            "cardinality": "single",
                            "readonly": false,
                            "label": "Decimal",
                            "description": "unlimited"
                        },
                        {
                            "name": "tenKolibri:intsingle",
                            "type": "integer",
                            "defaultvalue": 0,
                            "required": false,
                            "cardinality": "single",
                            "readonly": false,
                            "label": "Integer",
                            "description": "unlimited"
                        },
                        {
                            "name": "tenKolibri:datesingle",
                            "type": "datetime",
                            "required": false,
                            "cardinality": "single",
                            "resolution": "date",
                            "readonly": false,
                            "label": "Date2",
                            "description": "unlimited"
                        },
                        {
                            "name": "tenKolibri:datetimesingle",
                            "type": "datetime",
                            "required": false,
                            "cardinality": "single",
                            "readonly": false,
                            "label": "Date & time",
                            "description": "unlimited"
                        },
                        {
                            "name": "tenKolibri:booleannull",
                            "type": "boolean",
                            "required": false,
                            "cardinality": "single",
                            "readonly": false,
                            "label": "Boolean Tri-State",
                            "description": "Null allowed"
                        }
                    ],
                    "layout": {
                        "align": "column"
                    },
                    "label": "Without obligation"
                }
            ]
        }
    ],
    "label": "QA-DocAllSingleFields (alt)",
    "description": "05 Quality Assurance"
}
